import {
  LayoutDashboard,
  Database,
  Shield,
  Wrench,
  Flame,
  Droplets,
  Users,
  AlertTriangle,
  ShieldCheck,
  Truck,
  HardHat,
  ClipboardCheck,
  FileText,
  Calendar,
  GraduationCap,
  Award,
  BarChart3,
  FileBarChart,
  FileSpreadsheet,
  FileCheck,
  Activity,
  Target,
  ScrollText,
  ClipboardList,
  RefreshCw,
  UserCog,
  BookOpen,
  AlertCircle,
  Radio,
  CalendarDays,
} from 'lucide-react';
import type { MenuItem } from '../types/navigation';

export const menuItems: MenuItem[] = [
  {
    label: 'Dashboard',
    icon: LayoutDashboard,
    path: '/',
    description: 'Visão geral do sistema com indicadores e métricas operacionais.',
  },
  {
    label: 'Cadastro',
    icon: Database,
    adminOnly: true,
    children: [
      {
        label: 'Bombeiros',
        icon: Shield,
        path: '/cadastro/bombeiros',
        description: 'Cadastro de bombeiros e equipes operacionais.',
        adminOnly: true,
      },
      {
        label: 'APOC',
        icon: Radio,
        path: '/cadastro/apoc',
        description: 'Centro de Operações Aeroportuárias — pessoal MOTIVA.',
        adminOnly: true,
      },
      {
        label: 'Equipamentos',
        icon: Wrench,
        path: '/cadastro/equipamentos',
        description: 'Cadastro e manutenção de equipamentos operacionais.',
      },
      {
        label: 'Extintores',
        icon: Flame,
        path: '/cadastro/extintores',
        description: 'Controle de agentes extintores e recargas.',
      },
      {
        label: 'Hidrantes',
        icon: Droplets,
        path: '/cadastro/hidrantes',
        description: 'Gestão de hidrantes e pontos de água.',
      },
      {
        label: 'Viaturas',
        icon: Truck,
        path: '/cadastro/viaturas',
        description: 'Cadastro de viaturas operacionais.',
        adminOnly: true,
      },
      {
        label: 'Gerenciar Documentos',
        icon: FileText,
        path: '/cadastro/documentos',
        description: 'Templates de documentos para preenchimento e assinatura.',
        adminOnly: true,
      },
    ],
  },
  {
    label: 'Funcionários',
    icon: Users,
    children: [
      {
        label: 'Todos',
        icon: Users,
        path: '/funcionarios',
        description: 'Visualização de todos os funcionários cadastrados.',
      },
      {
        label: 'EPIs',
        icon: HardHat,
        path: '/epis',
        description: 'Controle de Equipamentos de Proteção Individual.',
      },
      {
        label: 'Certificações',
        icon: Award,
        path: '/certificacoes',
        description: 'Gestão de certificações e licenças NR.',
      },
      {
        label: 'Férias',
        icon: CalendarDays,
        path: '/cadastro/ferias',
        description: 'Controle de férias do efetivo.',
      },
    ],
  },
  {
    label: 'Registros Diários',
    icon: BookOpen,
    children: [
      {
        label: 'LRO',
        icon: FileSpreadsheet,
        path: '/registros-diarios/lro',
        description: 'Lista de Ronda Operacional - preenchimento diário.',
      },
      {
        label: 'PTR-BA',
        icon: FileText,
        path: '/registros-diarios/ptr-ba',
        description: 'Plano de Trabalho de Ronda - Bombeiro de Aeródromo.',
      },
      {
        label: 'LRO/Ocorrências',
        icon: AlertCircle,
        path: '/registros-diarios/lro-ocorrencias',
        description: 'Registro de ocorrências durante o plantão para inclusão automática no LRO.',
      },
    ],
  },
  {
    label: 'Ocorrências',
    icon: AlertTriangle,
    path: '/ocorrencias',
    description: 'Registro de ocorrências operacionais — BONA e RAE.',
  },
  {
    label: 'Inspeções Operacionais',
    icon: ShieldCheck,
    path: '/inspecoes',
    description: 'Gestão de inspeções de segurança e conformidade.',
  },
  {
    label: 'Viaturas CCI',
    icon: Truck,
    path: '/viaturas',
    description: 'Controle e monitoramento de viaturas do CCI.',
  },
  {
    label: 'Documentos',
    icon: FileText,
    children: [
      {
        label: 'Trocas de Serviço',
        icon: RefreshCw,
        path: '/documentos/trocas',
        description: 'Formulário de Troca de Serviços (Permuta).',
      },
      {
        label: 'Checklists',
        icon: ClipboardCheck,
        path: '/checklists',
        description: 'Criação e aplicação de checklists operacionais.',
      },
      {
        label: 'Escalas',
        icon: Calendar,
        path: '/escalas',
        description: 'Gestão de escalas de trabalho.',
      },
      {
        label: 'Agentes Extintores',
        icon: Flame,
        path: '/cadastro/extintores',
        description: 'Controle de agentes extintores e recargas.',
      },
      {
        label: 'Ordens de Serviço',
        icon: ClipboardList,
        path: '/relatorios/ordem-servico',
        description: 'Controle de ordens de serviço.',
      },
    ],
  },
  {
    label: 'Treinamentos',
    icon: GraduationCap,
    children: [
      {
        label: 'Outros',
        icon: GraduationCap,
        path: '/treinamentos',
        description: 'Controle de treinamentos e capacitações.',
      },
      {
        label: 'TP/EPR',
        icon: ScrollText,
        path: '/treinamentos/tp-epr',
        description: 'Teste de Progressão / Exame de Progressão.',
      },
      {
        label: 'TAF',
        icon: Target,
        path: '/treinamentos/taf',
        description: 'Teste de Aptidão Física.',
      },
    ],
  },
  {
    label: 'Estatísticas',
    icon: BarChart3,
    path: '/estatisticas',
    description: 'Análise de dados e estatísticas operacionais.',
  },
  {
    label: 'Relatórios',
    icon: FileBarChart,
    children: [
      {
        label: 'LRO',
        icon: FileSpreadsheet,
        path: '/relatorios/lro',
        description: 'Lista de Ronda Operacional.',
      },
      {
        label: 'BONA',
        icon: FileCheck,
        path: '/relatorios/bona',
        description: 'Boletim de Ocorrência e Notificação de Acidente.',
      },
      {
        label: 'PTR-BA',
        icon: FileText,
        path: '/relatorios/ptr-ba',
        description: 'Plano de Trabalho de Ronda - Bombeiro de Aeródromo.',
      },
      {
        label: 'Exercícios',
        icon: Activity,
        children: [
          {
            label: 'TAF',
            icon: Target,
            path: '/relatorios/exercicios/taf',
            description: 'Teste de Aptidão Física.',
          },
          {
            label: 'TP/EPR',
            icon: ScrollText,
            path: '/relatorios/exercicios/tp-epr',
            description: 'Teste de Progressão / Exame de Progressão.',
          },
        ],
      },
      {
        label: 'Ordem de Serviço',
        icon: ClipboardList,
        path: '/relatorios/ordem-servico',
        description: 'Controle de ordens de serviço.',
      },
      {
        label: 'Trocas',
        icon: RefreshCw,
        path: '/relatorios/trocas',
        description: 'Registro de trocas de plantão e equipamentos.',
      },
    ],
  },
  {
    label: 'Usuários',
    icon: UserCog,
    path: '/usuarios',
    description: 'Gerenciamento de usuários do sistema.',
    adminOnly: true,
  },
];
