CREATE TABLE IF NOT EXISTS treinamentos_taf (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  equipe TEXT NOT NULL DEFAULT '',
  numero INTEGER NOT NULL DEFAULT 0,
  ano TEXT NOT NULL DEFAULT '',
  data TEXT NOT NULL DEFAULT '',
  hora TEXT NOT NULL DEFAULT '',
  turno TEXT NOT NULL DEFAULT '',
  tipo_taf TEXT NOT NULL DEFAULT '',
  p1_nome TEXT NOT NULL DEFAULT '', p1_funcao TEXT NOT NULL DEFAULT '', p1_idade INTEGER NOT NULL DEFAULT 0, p1_tempo TEXT NOT NULL DEFAULT '',
  p2_nome TEXT NOT NULL DEFAULT '', p2_funcao TEXT NOT NULL DEFAULT '', p2_idade INTEGER NOT NULL DEFAULT 0, p2_tempo TEXT NOT NULL DEFAULT '',
  p3_nome TEXT NOT NULL DEFAULT '', p3_funcao TEXT NOT NULL DEFAULT '', p3_idade INTEGER NOT NULL DEFAULT 0, p3_tempo TEXT NOT NULL DEFAULT '',
  p4_nome TEXT NOT NULL DEFAULT '', p4_funcao TEXT NOT NULL DEFAULT '', p4_idade INTEGER NOT NULL DEFAULT 0, p4_tempo TEXT NOT NULL DEFAULT '',
  p5_nome TEXT NOT NULL DEFAULT '', p5_funcao TEXT NOT NULL DEFAULT '', p5_idade INTEGER NOT NULL DEFAULT 0, p5_tempo TEXT NOT NULL DEFAULT '',
  p6_nome TEXT NOT NULL DEFAULT '', p6_funcao TEXT NOT NULL DEFAULT '', p6_idade INTEGER NOT NULL DEFAULT 0, p6_tempo TEXT NOT NULL DEFAULT '',
  p7_nome TEXT NOT NULL DEFAULT '', p7_funcao TEXT NOT NULL DEFAULT '', p7_idade INTEGER NOT NULL DEFAULT 0, p7_tempo TEXT NOT NULL DEFAULT '',
  p8_nome TEXT NOT NULL DEFAULT '', p8_funcao TEXT NOT NULL DEFAULT '', p8_idade INTEGER NOT NULL DEFAULT 0, p8_tempo TEXT NOT NULL DEFAULT '',
  p9_nome TEXT NOT NULL DEFAULT '', p9_funcao TEXT NOT NULL DEFAULT '', p9_idade INTEGER NOT NULL DEFAULT 0, p9_tempo TEXT NOT NULL DEFAULT '',
  p10_nome TEXT NOT NULL DEFAULT '', p10_funcao TEXT NOT NULL DEFAULT '', p10_idade INTEGER NOT NULL DEFAULT 0, p10_tempo TEXT NOT NULL DEFAULT '',
  observacoes TEXT NOT NULL DEFAULT '',
  chefe_equipe TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo')::TEXT,
  updated_at TEXT NOT NULL DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo')::TEXT
);
CREATE INDEX IF NOT EXISTS idx_taf_equipe ON treinamentos_taf(equipe);
CREATE INDEX IF NOT EXISTS idx_taf_ano ON treinamentos_taf(ano);
CREATE INDEX IF NOT EXISTS idx_taf_data ON treinamentos_taf(data);
ALTER TABLE treinamentos_taf ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS taf_all ON treinamentos_taf;
CREATE POLICY taf_all ON treinamentos_taf FOR ALL USING (true) WITH CHECK (true);
